### PR TITLE
Fixes #303: Add application/json to the list of JSON mime types

### LINKED ISSUE #303: Add "application/json" to the list of processable javascript type blocks
Using version 1.17.10

**Description**
Script blocks with type `application/json` are not getting minified to a single line.  If I change the type to `application/ld+json` it all works.

**To Reproduce**
Input contains 
`<script id=priceStakDataModel type=application/json>  
  {"selectedTab":"buy"}  
</script>`

**Minified output or stack trace**
minifiedoutput

**Excepted output code**
`<script id=priceStakDataModel type=application/json>{"selectedTab":"buy"}</script>`

I'm planning to submit a PR for this as it's an extension of #66

### PR DESCRIPTION
**Pull request by AndyMcKenna**
Not sure how to get the formatting correct here

### CODE REVIEW

**Comment by trullock** [comment]
Thanks for this, surely this sould match the `application/ld+json` implementation. i.e. why does that get treated as JS and yours as JSON?

Presumably they should both be json?

**Comment by AndyMcKenna** [comment]
It looks like since `application/json` isn't currently a case in the switch, it's getting set to `HtmlScriptStyleElement.NA`

**Comment by trullock** [comment]
Yeah but I meant your change has highlighted that perhaps the `ld+json` varient isnt being treated properly

**Comment by AndyMcKenna** [comment]
From what I can tell, `ld+json` is working correctly.  When I switched my script blocks in my html to that type from `application/json`, everything minimized correctly.

**Comment by trullock** [comment]
Closing this PR as it doesn't include tests. Fixing the issues separately now...

**Pull request closed without merging**
