### PR TITLE
Fix issue 345

### PR DESCRIPTION
**Pull request by zhangyiatmicrosoft**
#345 run-time error JS1292: Strict-mode does not allow duplicate property names

Cannot find any doc regarding how to run tests or add news. I'd be happy to add them!

### CODE REVIEW

**Comment by trullock** [comment]
To add a test add a method to https://github.com/trullock/NUglify/blob/master/src/NUglify.Tests/JavaScript/Bugs.cs and then create the input and expected files under https://github.com/trullock/NUglify/tree/master/src/NUglify.Tests/TestData/JS

**Comment by trullock** [comment]
👍 will review asap

**Comment by zhangyiatmicrosoft** [comment]
Is there anything different between nuglifyapp and the test runner? As you can see below the app is giving correct result

<pre>
D:\repo\ghlink\my-NUglify\src\NUglifyApp\bin\Debug>NUglifyApp.exe ..\..\..\NUglify.Tests\TestData\JS\Input\Bugs\Bug345.js
NUglifyApp (version 1.0.0.0)
Copyright (c)  2016

Minifying 'D:\repo\ghlink\my-NUglify\src\NUglifyApp\bin\Debug\..\..\..\NUglify.Tests\TestData\JS\Input\Bugs\Bug345.js'

Original Size: 279 bytes; reduced size: 100 bytes (64.2% minification)
Gzip of source input approx. 129 bytes (53.8% compression)
Gzip of minified output approx. 87 bytes (68.8% compression)

"use strict";function test1({n=1,t=2}={}){console.log(n+t)}function test2(n=1,t=2){console.log(n+t)}
</pre>

**Review by trullock — CHANGES_REQUESTED** [review]
Can you revert all of the whitespace changes youve made please

**Comment by zhangyiatmicrosoft** [comment]
> Can you revert all of the whitespace changes youve made please

I assume you prefer spaces, not TABs? Checked carefully line 3369, and 3373 to 3380 had TABs before my change.
Anyhow, I changed them all to spaces.

**Comment by trullock** [comment]
Unfortunately the codebase has a mix, I inherited it.
Your commits had changed a bunch of whitespace on lines that were otherwise untouched, that was my issue which you've now fixed. It made the diff hard to read.
Are you done now? I'll review test and merge

**Comment by zhangyiatmicrosoft** [comment]
> Unfortunately the codebase has a mix, I inherited it. Your commits had changed a bunch of whitespace on lines that were otherwise untouched, that was my issue which you've now fixed. It made the diff hard to read. Are you done now? I'll review test and merge

Yes please review. I think at least that segment is easier to read and more consistent now

**Comment by zhangyiatmicrosoft** [comment]
@trullock any updates

**Pull request merged**
