### PR TITLE
Fix bug #264

### PR DESCRIPTION
**Pull request by rwasef1830**
WIP

### CODE REVIEW

**Comment by rwasef1830** [comment]
@trullock There's a comment explicitly written near that line that this is an implicit property that should not have the same structure as a normal property. I just updated the visitor to try taking binding name of function object. It now passes.

**Comment by trullock** [comment]
Re the comment, the thing to know is that this codebase was written for ES4, so I wouldn't trust comments blindly. That comment and the line you quoted above stink of a poorly implemented feature. There are probably other symptoms relating to this

**Comment by rwasef1830** [comment]
Well that kind of major heart surgery can cause a ton of regressions, I'm not comfortable enough to do that myself though :-(
I hope this gets merged at least to unblock me and then the major reworking can be done in the future

**Comment by rwasef1830** [comment]
To clarify this comment explicitly mentions ES6 and explicitly tells not to set the name field:

https://github.com/trullock/NUglify/blob/ef1ac17750a9390aec65ebba49a6cd6f9025c6ac/src/NUglify/JavaScript/JSParser.cs#L4920-L4922

**Pull request merged**
