### PR TITLE
Fixes #87

### LINKED ISSUE #87: PreserveFunctionNames Js Settings
When I set PreserveFunctionNames = true, Nuglify changes some functions names:

Example:

	CodeSettings settings = new CodeSettings();
	settings.ReorderScopeDeclarations = false;
	settings.RemoveFunctionExpressionNames = false;
	settings.RemoveUnneededCode = false;
	settings.TermSemicolons = true;
	settings.PreserveFunctionNames = true;
	var result = Uglify.Js("function a(){this.prueba=prueba2; function prueba2(){alert(hola);}", settings);

Prueba2 function changes his name.

### PR DESCRIPTION
**Pull request by life777**
Fixes #87

Fix bug with preserving functions names in function declaration. Fix is easy and described in Fixes #87

### CODE REVIEW

**Comment by trullock** [comment]
Can we add some tests to the project that prove this fixes the given case please?

**Comment by life777** [comment]
@trullock 
Yes, sure

**Comment by trullock** [comment]
We need to work out why the test introduced by https://github.com/trullock/NUglify/pull/109 doesn't reproduce this

**Comment by life777** [comment]
@trullock 
It looks strange because when I copy/paste your test code it renames `prueba2` to `n`.
I build NUglify for netstandard2.0 and use it on Linux. Probably it may be the cause of the different results.

**Comment by trullock** [comment]
Any chance of getting those tests? ;)

**Comment by trullock** [comment]
@life777 how are you invoking nuglify to be able to reproduce the issue?

**Comment by trullock** [comment]
Closing this due to lack of tests and response.

Will fix this issue fully, separately

**Pull request closed without merging**
