### PR TITLE
Fix: LineBreak within optional chaining

### PR DESCRIPTION
**Pull request by AndreasHoffmann2**
We got an error from the minified code in the browser:

MicrosoftTeams-image

The linebreak between "?" and "." should not be there.

The code attached should do the trick I guess.

### CODE REVIEW

**Comment by trullock** [comment]
Looks right, will merge asap

**Comment by AndreasHoffmann2** [comment]
Since we hit another very similar issue, I created a unit-test for this. And the fix above does not fix the issue.
I'll close this for the moment.

**Comment by AndreasHoffmann2** [comment]
We created a unit test and did now really fix the issue.

**Comment by trullock** [comment]
Looks good, will merge asap

**Comment by AndreasHoffmann2** [comment]
We found several other issues with the line-breaks and are currently working on a generic test and the necessary fixes. Please do not merge this one for the moment.

**Comment by AndreasHoffmann2** [comment]
Closed since we have a better test now.

**Comment by AndreasHoffmann2** [comment]
https://github.com/trullock/NUglify/pull/338

**Pull request closed without merging**
