### PR TITLE
Bug #353

### PR DESCRIPTION
**Pull request by failwyn**
added Test Case for Bug #353
added delete to CanBeIdentifier (#353)

### CODE REVIEW

**Comment by trullock** [comment]
Looks good, can you revert the whitespace changes please

**Comment by failwyn** [comment]
Will do, I thought I ignored them all, don't know how I missed the JSKeyword.cs file...

**Comment by failwyn** [comment]
I can't get it to stop showing the changes for two lines...

Bugs.cs
line 1: using System.IO;
JSKeyword.js
line 81: case JSToken.Native: return "native";

**Comment by trullock** [comment]
No worries, thats fine.

The whitespace in this repo is a mess but lets try not to make it worse.

Those changes are probably for the better

**Comment by failwyn** [comment]
I use an extension to remove all trailing whitespace, it becomes a pain in the neck when working on other repos... I'll be more mindful in the future when staging changes. Thanks again for this!

**Pull request merged**
